#!/bin/bash


#Storing the file names in an Array 
declare -a filenames=(0-iam_betty 1-who_am_i 10-mirror_permissions 100-change_owner_and_group 101-symbolic_link_permissions 102-if_only 103-Star_Wars 11-directories_permissions 12-directory_permissions 13-change_group 2-groups 3-new_owner 4-empty 5-execute 6-multiple_permissions 7-everybody 8-James_Bond 9-John_Doe)


#creating the files
for filename in ${filenames[@]}

    #deleting all the files
    do
        rm $filename
done