#!/bin/bash

declare -a filenames=(0-iam_betty 1-who_am_i 10-mirror_permissions 100-change_owner_and_group 101-symbolic_link_permissions 102-if_only 103-Star_Wars 11-directories_permissions 12-directory_permissions 13-change_group 2-groups 3-new_owner 4-empty 5-execute 6-multiple_permissions 7-everybody 8-James_Bond 9-John_Doe)

#creating the files
for filename in ${filenames[@]}
do
echo \#\!/bin/bash >> $filename
chmod u+x $filename
done

echo "su betty" >> 0-iam_betty 
echo "whoami" >> 1-who_am_i 
echo "chmod --reference=olleh hello" >> 10-mirror_permissions 
echo "chown  vincent:staff *" >> 100-change_owner_and_group 
echo "chown -h vincent:staff _hello" >> 101-symbolic_link_permissions 
echo "chown --from=guillaume betty hello" >> 102-if_only
echo "telnet towel.blinkenlights.nl" >> 103-Star_Wars
echo "chmod -R +X ." >> 11-directories_permissions 
echo "mkdir -m 751 my_dir" >> 12-directory_permissions
echo "chgrp school hello" >> 13-change_group
echo "groups" >> 2-groups 
echo "chown betty hello" >> 3-new_owner
echo "touch hello" >> 4-empty
echo "chmod u+x hello" >> 5-execute
echo "chmod ug+x,o+r hello" >> 6-multiple_permissions
echo "chmod +x hello" >> 7-everybody
echo "chmod 007 hello" >> 8-James_Bond
echo "chmod 753 hello" >> 9-John_Doe


# Un-comment this if you want to commit the changes and push to your git repositor
#git add .
#git commit -m "commit using script"
#git push 